# group_vars/all.yml
# Variables visible to all nodes
---
# Install Ansible Docker module dependencies
pip_install_packages:
  - name: requests
    version: "<2.2.29" # See: https://github.com/docker/docker-py/issues/3113

# Allow vagrant user and Jenkins to run Docker commands
docker_users:
  - vagrant

# Install Docker Compose
docker_install_compose_plugin: true
docker_install_compose: false
