version: '3'

services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/database
    environment:
      - MONGO_URL=mongodb://database:27017/animals
    depends_on:
      - database

  database:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  test:
    build: .
    command: yarn test
    environment:
      - API_URL=http://webapp:3000
    depends_on:
      - webapp

volumes:
  mongo_data:
